version: '3'

services:
  app-dev:
    container_name: crvx_client_dev
    restart: on-failure
    build:
      context: ..
      dockerfile: ./Dockerfile
    volumes:
      - ../public:/usr/share/nginx/html:rw
      - ../nginx.conf:/etc/nginx/conf.d/default.conf:rw
    environment:
      - NODE_ENV=development
    ports:
      - '8080:80'
    command: ['nginx', '-g', 'daemon off;']

volumes:
  app-dev:
