version: '3'

services:
  app:
    container_name: crvx_client
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NODE_ENV=production
    networks:
      - default
      - web
    command: ['nginx', '-g', 'daemon off;']
    labels:
      - 'traefik.docker.network=web'
      - 'traefik.enable=true'
      - 'traefik.domain=crvx.fr'
      - 'traefik.basic.frontend.rule=Host:crvx.fr'
      - 'traefik.basic.port=80'
      - 'traefik.basic.protocol=http'
      - 'traefik.frontend.headers.SSLRedirect=true'
      - 'traefik.frontend.headers.STSSeconds=315360000'
      - 'traefik.frontend.headers.browserXSSFilter=true'
      - 'traefik.frontend.headers.contentTypeNosniff=true'
      - 'traefik.frontend.headers.forceSTSHeader=true'
      - "traefik.frontend.headers.contentSecurityPolicy=default-src 'self';frame-ancestors 'self';style-src 'self';script-src 'self';img-src 'self';font-src 'self'"
      - 'traefik.frontend.headers.referrerPolicy=no-referrer'
      - 'traefik.frontend.headers.frameDeny=true'

networks:
  web:
    external: true
